<img src = "https://drive.google.com/uc?export=view&id=1rSrsZ04aJ_D3BC67Cy2dBUZ6tmguydNf" alt = "Encabezado MLDS" width = "100%">  </img>

# **Entendimiento y carga de los datos**
---

Este notebook es una plantilla que le puede servir como guía para el tercer entregable del proyecto aplicado.

## **0. Integrantes del equipo de trabajo**
---

1. ---**Eduardo Elias Castellanos Picon CC 1068390127 <eduardoeliascastellanospicon@gmail.com>**---
2. ---**Anthony Joao Parra CC 1073165713 <anthonyjoaoparra@gmail.com>**---
3. ---**Asdrúval Zácipa Corredor CC 79139929 <azacipac@unal.edu.co>**---

## **1. Análisis Exploratorio de los Datos**
---

Describa la estructura y la naturaleza de los datos antes de comenzar con el análisis en profundidad.

### **1.1. Resumen General**
---

- ¿Cuántos documentos tiene el *dataset*?
- ¿En qué formato están guardados los datos?
- ¿Qué tamaño en MB tiene el conjunto?

---**INGRESE SU RESPUESTA**---
- ¿Cuántos documentos tiene el *dataset*?

El dataset a analizar ha sido descargado desde la página oficial del ICFES (https://www.icfes.gov.co/web/guest/data-icfes). Corresponde a los resultados del examen Saber11 entre los años 2017 y 2023. El archivo se encuentra en formato ZIP (ResultadosSaber11_2027_2022_Fte_ICFES.zip) e incluye a su vez 13 archivos comprimidos denominados:

SB11_20171.zip
SB11_20172.zip
SB11_20181.zip
SB11_20182.zip
SB11_20191.zip
SB11_20192.zip
SB11_20201.zip
SB11_20202.zip
SB11_20211.zip
SB11_20212.zip
SB11_20221.zip
SB11_20222.zip
SB11_20231.zip

- ¿En qué formato están guardados los datos?

Internamente cada ZIP incluye un archivo de texto denominado SB11_YYYY[12].TXT, con encabezados y campos separados por TAB. El archivo ZIP inicial se descomprime en una carpeta con el mismo nombre que es la que será procesada.

- ¿Qué tamaño en MB tiene el conjunto?

El tamaño total del archivo a procesar es de 362MB

El siguiente código es el utilizado para realizar la lectura y extracción de los datos del archivo ZIP y el cargue al dataframe de trabajo. En primera instancia se cargan las librerias necesarias.

In [ ]:
import pandas as pd
import zipfile
import os
import copy
import warnings
from pathlib import Path
from IPython.display import display

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
warnings.filterwarnings("ignore") # suprimir mensajes warning
path_i = "./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/" # variable que indica el nombre del archivo ZIP contenedor

In [ ]:
def read_zip_file(filename):
    """"
    Función read_zip_file: Realiza la extracción de los datos de cada archivo zip y devuelve un dataframe por cada uno de los archivos TXT

    Parámetros:
        filanema(string): Nombre del archivo a analizar incluyendo la ruta de ubicación del mismo

    Return:
        df   (dataframe): Dataframe con los datos del archivo procesado

    Ejemplo:

        >>> df = read_zip_file(filename = './data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20171.zip')

            *** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20171.zip
              zipfile SB11_20171.TXT
    """
    print("*** processing filename", filename)
    with zipfile.ZipFile(filename) as z:
        file = z.namelist()[0]
        print("  zipfile",file)
        with z.open(file) as f:
            df = pd.read_csv(f, header=0, delimiter="¬")
    return df

In [ ]:
# en este segmento de codigo se procesa el archivo zip y se extraen los diferentes archivos TXT a diccionario de dataframes
obj = os.walk(path_i)
ind = 1
dict_of_df = {}
frames = []
print("*** searching files")
for root, dirs, files in obj: # Procesar todos los archivos que se encuentran en el directorio
    for entry in files:
        if (entry.endswith(".zip")):
            file_i = path_i + entry
            print("archivo", file_i)
            key_name = 'df_' + Path(os.path.basename(file_i)).stem
            frames.append(Path(os.path.basename(file_i)).stem)
            df = read_zip_file(filename = file_i)
            # se cargan los dataframes en un diccionario cuya clave es el nombre que se le da al dataframe
            dict_of_df[key_name] = copy.deepcopy(df)
print("done")

*** searching files
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20171.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20171.zip
  zipfile SB11_20171.TXT
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20172.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20172.zip
  zipfile SB11_20172.TXT
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20181.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20181.zip
  zipfile SB11_20181.TXT
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20182.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20182.zip
  zipfile SB11_20182.TXT
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20191.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20191.zip
  zipfile SB11_20191/SB11_20191_.txt
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20192.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20192.zip
  zipfile SB11_20192.TXT
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20201.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20201.zip
  zipfile SB11_20201.txt
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20202.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20202.zip
  zipfile SB11_20202.txt
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20211.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20211.zip
  zipfile SB11_20211.txt
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20212.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20212.zip
  zipfile SB11_20212.txt
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20221.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20221.zip
  zipfile SB11_20221.TXT
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20222.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20222.zip
  zipfile SB11_20222.TXT
archivo ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20231.zip
*** processing filename ./data/input/ResultadosSaber11_2027_2022_Fte_ICFES/SB11_20231.zip
  zipfile SB11_20231.TXT
done

### **1.2. Exploración Preliminar**
---
- ¿Cuál es la naturaleza de los datos que se van a analizar en el proyecto?
- ¿Qué tipos de variables y características están presentes en el conjunto de datos?

---**INGRESE SU RESPUESTA**---

- ¿Cuál es la naturaleza de los datos que se van a analizar en el proyecto?

Al revisar los dataframes generados, encontramos que en cada uno de los datasets se encuentran datos de tipo numerico y carácter que corresponden a características de la prueba Saber11 presentada por el estudiante. Los datos se pueden clasificar en los siguientes grupos:

-- Datos cuantitativos: Corresponden a los resultados de la prueba Saber11 en sus diferentes asignaturas. Se reportan los siguientes:

PUNT_LECTURA_CRITICA: Númerico con valor entre 1 y 100

PERCENTIL_LECTURA_CRITICA: Númerico correspondiente al percentil en el que se encuentra el puntaje del estudiante en esta prueba

DESEMP_LECTURA_CRITICA: Númerico de 4 niveles correspondiente a los siguientes rangos: Nivel 1 [0, 35], Nivel 2 [36, 50], Nivel 3 [51, 65], Nivel 4 [66, 100]

PUNT_MATEMATICAS: Númerico con valor entre 1 y 100

PERCENTIL_MATEMATICAS: Númerico correspondiente al percentil en el que se encuentra el puntaje del estudiante en esta prueba

DESEMP_MATEMATICAS: Númerico de 4 niveles correspondiente a los siguientes rangos: Nivel 1 [0, 35], Nivel 2 [36, 50], Nivel 3 [51, 70], Nivel 4 [71, 100]

PUNT_C_NATURALES: Númerico con valor entre 1 y 100

PERCENTIL_C_NATURALES: Númerico correspondiente al percentil en el que se encuentra el puntaje del estudiante en esta prueba

DESEMP_C_NATURALES: Númerico de 4 niveles correspondiente a los siguientes rangos: Nivel 1 [0, 40], Nivel 2 [41, 55], Nivel 3 [56, 70], Nivel 4 [71, 100]

PUNT_SOCIALES_CIUDADANAS: Númerico con valor entre 1 y 100

PERCENTIL_SOCIALES_CIUDADANAS: Númerico correspondiente al percentil en el que se encuentra el puntaje del estudiante en esta prueba

DESEMP_SOCIALES_CIUDADANAS: Númerico de 4 niveles correspondiente a los siguientes rangos: Nivel 1 [0, 40], Nivel 2 [41, 55], Nivel 3 [56, 70], Nivel 4 [71, 100]

PUNT_INGLES: Númerico con valor entre 1 y 100. El valor -1 indica que el estudiante no contesto las preguntas de ésta prueba

PERCENTIL_INGLES: Númerico correspondiente al percentil en el que se encuentra el puntaje del estudiante en esta prueba

DESEMP_INGLES: Caractér de 4 niveles correspondiente a los siguientes rangos: PreA1 [0, 36], A1 [37, 57], A2 [58, 70], B1 [71, 100]

PUNT_GLOBAL: Númerico con valor entre 1 y 500

PERCENTIL_GLOBAL: Númerico correspondiente al percentil en el que se encuentra el puntaje del estudiante respecto al puntaje global de la prueba

-- Variables que dan información del estudiante:

ESTU_TIPODOCUMENTO: Tipo de documento del estudiante

ESTU_NACIONALIDAD: Nacionalidad del estudiante

ESTU_GENERO: Género del estudiante

ESTU_FECHANACIMIENTO: Fecha de nacimiento del estudiante

PERIODO: Período de presentacion de la prueba Saber11

ESTU_CONSECUTIVO: Identificador único de la prueba presentada por el estudiante

ESTU_ESTUDIANTE: Valor constante ESTUDIANTE

ESTU_PAIS_RESIDE: Nombre del país de residencia del estudiante

ESTU_TIENEETNIA: Respuesta a la pregunta ¿Pertenece usted a un grupo étnico minoritario?

ESTU_ETNIA: Descripción de la etnia indicada

ESTU_DEPTO_RESIDE: Nombre del departamento de residencia

ESTU_COD_RESIDE_DEPTO: Código del departamento de residencia

ESTU_MCPIO_RESIDE: Nombre del municipio de residencia

ESTU_COD_RESIDE_MCPIO: Código del municipio de residencia

ESTU_DEDICACIONLECTURADIARIA: Respuesta a la pregunta Usualmente, ¿cuánto tiempo al día dedica a leer por entretenimiento?

ESTU_DEDICACIONINTERNET: Respuesta a la pregunta Usualmente, ¿cuánto tiempo al día dedica a navegar en internet? Excluya actividades académicas

ESTU_HORASSEMANATRABAJA: Respuesta a la pregunta ¿Cuántas horas trabajó usted durante la semana pasada?

ESTU_TIPOREMUNERACION: Tipo de remuneracion si en la anterior variable se indico un valor mayor a 0

ESTU_PRIVADO_LIBERTAD: Indica si la persona que presento la prueba esta privada de la libertad.

ESTU_COD_MCPIO_PRESENTACION: Código de municipio de presentación de la prueba

ESTU_MCPIO_PRESENTACION: Nombre de municipio de presentación de la prueba

ESTU_DEPTO_PRESENTACION: Nombre departamento de presentación de la prueba

ESTU_COD_DEPTO_PRESENTACION: Código de departamento de presentación de la prueba

ESTU_INSE_INDIVIDUAL: Indice socioeconómico del estudiante

ESTU_NSE_INDIVIDUAL: Nivel socioeconómico a nivel del estudiante

ESTU_NSE_ESTABLECIMIENTO: Nivel socioeconómico de la institucion educativa de secundaria

ESTU_ESTADOINVESTIGACION: Identifica los usuarios que están en proceso de investigación en el ICFES

-- Variables que dan información del entorno familiar:

FAMI_EDUCACIONPADRE: Nivel educativo más alto alcanzado por el padre

FAMI_EDUCACIONMADRE: Nivel educativo más alto alcanzado por la madre

FAMI_ESTRATOVIVIENDA: Estrato socioeconómico de la vivienda según recibo de energía eléctrica

FAMI_PERSONASHOGAR: Respuesta a la pregunta ¿Cuántas personas conforman el hogar donde vive actualmente, incluido usted?

FAMI_CUARTOSHOGAR: Respuesta a la pregunta En total, ¿en cuántos cuartos duermen las personas de su hogar?

FAMI_TIENEINTERNET: Respuesta a la pregunta ¿Su hogar cuenta con servicio o conexión a internet?

FAMI_TIENECOMPUTADOR: Respuesta a la pregunta ¿Cuáles de los siguientes bienes posee su hogar?: Computador

FAMI_TIENELAVADORA: Respuesta a la pregunta ¿Cuáles de los siguientes bienes posee su hogar?: Lavadora

FAMI_TIENEHORNOMICROOGAS: Respuesta a la pregunta ¿Cuáles de los siguientes bienes posee su hogar?: Horno Microondas

FAMI_TIENESERVICIOTV: Respuesta a la pregunta ¿Su hogar cuenta con servicio cerrado de televisión?

FAMI_TIENEAUTOMOVIL: Respuesta a la pregunta ¿Cuáles de los siguientes bienes posee su hogar?: Automóvil particular

FAMI_TIENEMOTOCICLETA: Respuesta a la pregunta ¿Cuáles de los siguientes bienes posee su hogar?: Motocicleta

FAMI_TIENECONSOLAVIDEOJUEGOS: Respuesta a la pregunta ¿Cuáles de los siguientes bienes posee su hogar?: Consola para juegos electrónicos (PlayStation, Xbox, Nintendo, etc.)

FAMI_NUMLIBROS: Respuesta a la pregunta ¿Cuántos libros físicos o electrónicos hay en su hogar excluyendo periódicos, revistas, directorios telefónicos y libros del colegio?

FAMI_COMELECHEDERIVADOS: Respuesta a la pregunta ¿Cuántas veces por semana se comen los siguientes alimentos en su hogar? Leche y/o sus derivados

FAMI_COMECARNEPESCADOHUEVO: Respuesta a la pregunta ¿Cuántas veces por semana se comen los siguientes alimentos en su hogar? Carne (pollo, pavo, res, cordero, cerdo, conejo, etc.), pescados o huevos

FAMI_COMECEREALFRUTOSLEGUMBRE: Respuesta a la pregunta ¿Cuántas veces por semana se comen los siguientes alimentos en su hogar? Cereal, frutas, legumbres

FAMI_TRABAJOLABORPADRE: Dedicación laboral del padre

FAMI_TRABAJOLABORMADRE: Dedicación laboral de la madre

FAMI_SITUACIONECONOMICA: Respuesta a la pregunta Con respecto al año inmediatamente anterior, la situación económica de su hogar es: Peor, Igual, Mejor

-- Variables que dan información del entorno escolar:

COLE_CODIGO_ICFES: Código ICFES del establecimiento educativo

COLE_COD_DANE_ESTABLECIMIENTO: Código DANE del establecimiento educativo

COLE_NOMBRE_ESTABLECIMIENTO: Nombre del establecimiento educativo

COLE_GENERO: Indica si es femenino, masculino o mixto

COLE_NATURALEZA: Indica si es oficial o privado

COLE_CALENDARIO: Indica el calendario académico

COLE_BILINGUE: Indica si es bilingue o no

COLE_CARACTER: Indica si es académico, técnico, etc.

COLE_COD_DANE_SEDE: Código DANE de la sede

COLE_NOMBRE_SEDE: Nombre de la sede

COLE_SEDE_PRINCIPAL: Indica si es la sede principal del establecimiento educativo

COLE_AREA_UBICACION: Indica si es urbano o rural

COLE_JORNADA: Jornada de la sede

COLE_COD_MCPIO_UBICACION: Código del municipio de ubicación

COLE_MCPIO_UBICACION: Nombre del municipio de ubicación

COLE_COD_DEPTO_UBICACION: Codigo del departamento de ubicación

COLE_DEPTO_UBICACION: Nombre del departamento de ubicación

- ¿Qué tipos de variables y características están presentes en el conjunto de datos?

Todas las variables son de tipo numérico o caracter

## **2. Análisis Descriptivo de los Datos**
---

Profundice en el análisis de los datos, proporcionando una descripción detallada y estadísticas clave.

### **2.1. Relaciones entre variables**
---

- ¿Se identifican patrones, tendencias o características notables?

- ¿Cómo se exploran y describen las relaciones entre variables?

---**INGRESE SU RESPUESTA**---

- ¿Se identifican patrones, tendencias o características notables?

Una primera exploración nos permite identificar los diferentes valores de las variables del dataset. En términos generales, todos los datasets tienen las mismas columnas, las cuales tienen valores literales y numéricos.

Las columnas con valores cuantitativos utilizaremos para efectos de estadísticas corresponden a las siguientes:

* PUNT_LECTURA_CRITICA: Númerico con valor entre 1 y 100
* PUNT_MATEMATICAS: Númerico con valor entre 1 y 100
* PUNT_C_NATURALES: Númerico con valor entre 1 y 100
* PUNT_SOCIALES_CIUDADANAS: Númerico con valor entre 1 y 100
* PUNT_INGLES: Númerico con valor entre 1 y 100. El valor -1 indica que el estudiante no contesto las preguntas de ésta prueba
* PUNT_GLOBAL: Númerico con valor entre 1 y 500

Otras características importantes a considerar son:

* ESTU_GENERO
* ESTU_DEPTO_RESIDE
* ESTU_COD_RESIDE_DEPTO
* ESTU_DEDICACIONLECTURADIARIA
* ESTU_DEDICACIONINTERNET
* ESTU_HORASSEMANATRABAJA

* FAMI_EDUCACIONPADRE
* FAMI_EDUCACIONMADRE
* FAMI_ESTRATOVIVIENDA
* FAMI_PERSONASHOGAR
* FAMI_CUARTOSHOGAR
* FAMI_TIENEINTERNET
* FAMI_TIENECOMPUTADOR
* FAMI_TIENELAVADORA
* FAMI_TIENEHORNOMICROOGAS
* FAMI_TIENESERVICIOTV
* FAMI_TIENEAUTOMOVIL
* FAMI_TIENEMOTOCICLETA
* FAMI_TIENECONSOLAVIDEOJUEGOS
* FAMI_NUMLIBROS
* FAMI_COMELECHEDERIVADOS
* FAMI_COMECARNEPESCADOHUEVO
* FAMI_COMECEREALFRUTOSLEGUMBRE
* FAMI_TRABAJOLABORPADRE
* FAMI_TRABAJOLABORMADRE
* FAMI_SITUACIONECONOMICA

* COLE_CODIGO_ICFES
* COLE_COD_DANE_ESTABLECIMIENTO
* COLE_NOMBRE_ESTABLECIMIENTO
* COLE_GENERO
* COLE_NATURALEZA
* COLE_CALENDARIO
* COLE_BILINGUE
* COLE_CARACTER
* COLE_COD_DANE_SEDE
* COLE_NOMBRE_SEDE
* COLE_SEDE_PRINCIPAL
* COLE_AREA_UBICACION
* COLE_JORNADA
* COLE_COD_MCPIO_UBICACION
* COLE_MCPIO_UBICACION
* COLE_COD_DEPTO_UBICACION
* COLE_DEPTO_UBICACION

In [ ]:
# validar los dataframes antes de concatenar
columnList = []
dictDf     = {}
for name_df in list(dict_of_df.keys()):
    print("\ndf",name_df)
    df = dict_of_df[name_df]
    display(df.head(5))
    columnList.append(df.columns)
    key_name = name_df
    dictDf[key_name] = df.columns
print("done")

df df_SB11_20171

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_ETNIA,...,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION
0,TI,COLOMBIA,M,19/06/2000,20171,SB11201710005624,ESTUDIANTE,COLOMBIA,No,NaN,...,4,80,80,B+,377,94,71.473010,NSE4,4.0,PUBLICAR
1,TI,COLOMBIA,F,02/09/2000,20171,SB11201710008394,ESTUDIANTE,COLOMBIA,No,NaN,...,1,52,38,A1,246,30,69.867787,NSE4,4.0,PUBLICAR
2,TI,COLOMBIA,F,25/05/2000,20171,SB11201710015727,ESTUDIANTE,COLOMBIA,No,NaN,...,3,50,35,A1,292,53,67.632333,NSE4,4.0,PUBLICAR
3,TI,COLOMBIA,M,08/02/1999,20171,SB11201710020106,ESTUDIANTE,COLOMBIA,No,NaN,...,2,79,79,B+,291,52,72.076829,NSE4,4.0,PUBLICAR
4,TI,COLOMBIA,F,20/08/1999,20171,SB11201710014735,ESTUDIANTE,COLOMBIA,No,NaN,...,3,78,76,B1,314,64,76.618628,NSE4,4.0,PUBLICAR

df df_SB11_20172

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_ETNIA,...,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION,ESTU_PILOPAGA
0,TI,COLOMBIA,M,22/11/1999,20172,SB11201720375526,ESTUDIANTE,COLOMBIA,No,NaN,...,49,55,A1,278,68,52.569676,NSE3,2.0,PUBLICAR,NO
1,TI,COLOMBIA,F,23/10/2000,20172,SB11201720374975,ESTUDIANTE,COLOMBIA,No,NaN,...,58,79,A2,287,73,42.479776,NSE2,2.0,PUBLICAR,NO
2,CC,COLOMBIA,M,01/11/2000,20172,SB11201720375021,ESTUDIANTE,COLOMBIA,No,NaN,...,40,20,A-,244,43,54.310264,NSE3,2.0,PUBLICAR,NO
3,TI,COLOMBIA,M,16/08/1999,20172,SB11201720374725,ESTUDIANTE,COLOMBIA,No,NaN,...,35,8,A-,187,7,48.012666,NSE2,2.0,PUBLICAR,NO
4,TI,COLOMBIA,F,21/01/2001,20172,SB11201720412450,ESTUDIANTE,COLOMBIA,No,NaN,...,55,73,A1,232,35,45.256781,NSE2,2.0,PUBLICAR,NO

df df_SB11_20181

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_ETNIA,...,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION,ESTU_PILOPAGA
0,TI,COLOMBIA,F,19/07/2000,20181,SB11201810005035,ESTUDIANTE,COLOMBIA,No,NaN,...,44,21,A-,226,20,54.101344,NSE3,3.0,PUBLICAR,NO
1,TI,COLOMBIA,M,03/10/2001,20181,SB11201810005012,ESTUDIANTE,COLOMBIA,No,NaN,...,58,45,A2,263,37,66.990405,NSE4,3.0,PUBLICAR,NO
2,TI,COLOMBIA,F,29/06/2000,20181,SB11201810005026,ESTUDIANTE,COLOMBIA,No,NaN,...,32,5,A-,204,12,45.721848,NSE2,3.0,PUBLICAR,NO
3,TI,COLOMBIA,M,30/04/2001,20181,SB11201810004998,ESTUDIANTE,COLOMBIA,No,NaN,...,50,32,A1,331,70,51.145124,NSE2,3.0,PUBLICAR,NO
4,TI,COLOMBIA,F,06/08/2001,20181,SB11201810005010,ESTUDIANTE,COLOMBIA,No,NaN,...,62,50,A2,318,63,53.365582,NSE3,3.0,PUBLICAR,NO

df df_SB11_20182

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_ETNIA,...,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_ESTADOINVESTIGACION,ESTU_GENERACION-E
0,CR,COLOMBIA,M,22/09/1999,20182,SB11201820540351,ESTUDIANTE,COLOMBIA,No,NaN,...,42.0,25,A-,177,6,2.0,45.885859,NSE2,PUBLICAR,NO
1,TI,COLOMBIA,M,29/12/2000,20182,SB11201820059515,ESTUDIANTE,COLOMBIA,No,NaN,...,41.0,22,A-,199,16,1.0,37.079030,NSE1,PUBLICAR,GENERACION E - GRATUIDAD
2,CC,COLOMBIA,F,22/04/1998,20182,SB11201820568196,ESTUDIANTE,COLOMBIA,No,NaN,...,38.0,14,A-,180,7,2.0,45.303861,NSE2,PUBLICAR,GENERACION E - GRATUIDAD
3,TI,COLOMBIA,F,30/05/2002,20182,SB11201820446686,ESTUDIANTE,COLOMBIA,No,NaN,...,44.0,31,A-,253,54,2.0,43.189222,NSE2,PUBLICAR,GENERACION E - GRATUIDAD
4,TI,COLOMBIA,F,20/11/2000,20182,SB11201820454103,ESTUDIANTE,COLOMBIA,No,NaN,...,29.0,1,A-,202,18,2.0,51.743335,NSE3,PUBLICAR,NO

df df_SB11_20191

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_DEPTO_RESIDE,...,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION,ESTU_GENERACIONE
0,TI,COLOMBIA,F,07/12/2000,20191,SB11201910008548,ESTUDIANTE,COLOMBIA,No,VALLE,...,54,39,A1,235,29,58.199482,3.0,3.0,PUBLICAR,NO
1,CC,COLOMBIA,F,23/03/1998,20191,SB11201910004475,ESTUDIANTE,COLOMBIA,No,VALLE,...,35,10,A-,217,21,51.018528,2.0,3.0,PUBLICAR,NO
2,TI,COLOMBIA,M,22/03/2001,20191,SB11201910011427,ESTUDIANTE,COLOMBIA,No,VALLE,...,49,32,A1,246,34,50.855656,2.0,3.0,PUBLICAR,NO
3,CC,COLOMBIA,M,16/06/1994,20191,SB11201910041975,ESTUDIANTE,COLOMBIA,No,VALLE,...,64,55,A2,255,38,52.688202,3.0,3.0,PUBLICAR,NO
4,CC,COLOMBIA,F,21/09/2000,20191,SB11201910014490,ESTUDIANTE,COLOMBIA,No,BOGOTA,...,71,64,B1,280,48,73.930832,4.0,4.0,PUBLICAR,NO

df df_SB11_20192

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_TIENEETNIA,ESTU_PAIS_RESIDE,ESTU_ETNIA,...,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION,ESTU_GENERACION-E
0,TI,COLOMBIA,M,18/02/2002,20194,SB11201940031558,ESTUDIANTE,No,COLOMBIA,NaN,...,54.0,67,A1,208,25.0,50.942156,2.0,2.0,PUBLICAR,NO
1,TI,COLOMBIA,F,24/01/2003,20194,SB11201940469859,ESTUDIANTE,No,COLOMBIA,NaN,...,64.0,89,A2,280,74.0,61.920976,3.0,3.0,PUBLICAR,NO
2,TI,COLOMBIA,M,28/06/2003,20194,SB11201940303339,ESTUDIANTE,No,COLOMBIA,NaN,...,63.0,88,A2,299,83.0,59.767864,3.0,4.0,PUBLICAR,NO
3,TI,COLOMBIA,M,02/06/2001,20194,SB11201940255017,ESTUDIANTE,No,COLOMBIA,NaN,...,64.0,89,A2,299,84.0,50.764238,2.0,3.0,PUBLICAR,GENERACION E - GRATUIDAD
4,TI,COLOMBIA,M,26/04/2002,20194,SB11201940154799,ESTUDIANTE,Si,COLOMBIA,Ninguno,...,53.0,67,A1,309,88.0,45.779135,2.0,3.0,PUBLICAR,GENERACION E - GRATUIDAD

df df_SB11_20201

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_DEPTO_RESIDE,...,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION,ESTU_GENERACION-E
0,CC,COLOMBIA,F,01/01/1985,20201,SB11202010045555,ESTUDIANTE,COLOMBIA,No,CESAR,...,36.0,7,A-,164,2.0,32.982652,1.0,1.0,VALIDEZ OFICINA JURÍDICA,GENERACION E - GRATUIDAD
1,CC,COLOMBIA,F,01/01/1995,20201,SB11202010045719,ESTUDIANTE,COLOMBIA,No,NARIÑO,...,30.0,3,A-,202,10.0,NaN,NaN,2.0,PUBLICAR,GENERACION E - GRATUIDAD
2,CC,COLOMBIA,F,01/01/1997,20201,SB11202010070662,ESTUDIANTE,COLOMBIA,Si,CAUCA,...,30.0,3,A-,162,2.0,37.868242,1.0,2.0,PUBLICAR,GENERACION E - GRATUIDAD
3,CC,COLOMBIA,F,01/01/2001,20201,SB11202010069926,ESTUDIANTE,COLOMBIA,No,PUTUMAYO,...,37.0,8,A-,188,6.0,54.880608,3.0,2.0,PUBLICAR,NO
4,CC,COLOMBIA,F,01/02/2001,20201,SB11202010023181,ESTUDIANTE,COLOMBIA,No,RISARALDA,...,80.0,80,B+,274,39.0,65.015303,4.0,4.0,PUBLICAR,NO

df df_SB11_20202

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_DEPTO_RESIDE,...,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION,ESTU_GENERACION-E
0,TI,COLOMBIA,M,03/07/2003,20204,SB11202040001656,ESTUDIANTE,COLOMBIA,No,CALDAS,...,48.0,61,A1,261,61,61.340840,3.0,3.0,PUBLICAR,NO
1,TI,COLOMBIA,F,16/06/2003,20204,SB11202040001763,ESTUDIANTE,COLOMBIA,No,BOGOTÁ,...,58.0,85,A2,306,87,71.825844,4.0,4.0,PUBLICAR,NO
2,TI,COLOMBIA,F,11/09/2003,20204,SB11202040001490,ESTUDIANTE,COLOMBIA,No,BOGOTÁ,...,51.0,71,A1,321,92,57.286312,3.0,3.0,PUBLICAR,NO
3,TI,COLOMBIA,M,05/03/2004,20204,SB11202040096445,ESTUDIANTE,COLOMBIA,No,BOGOTÁ,...,67.0,94,A2,338,96,67.476602,4.0,4.0,PUBLICAR,NO
4,TI,COLOMBIA,M,30/08/2003,20204,SB11202040048154,ESTUDIANTE,COLOMBIA,No,TOLIMA,...,29.0,1,A-,225,35,43.877158,2.0,2.0,PUBLICAR,GENERACION E - GRATUIDAD

df df_SB11_20211

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_DEPTO_RESIDE,...,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL,PERCENTIL_GLOBAL,ESTU_ESTADOINVESTIGACION
0,TI,COLOMBIA,M,05/11/2003,20211,SB11202110042506,ESTUDIANTE,COLOMBIA,No,VALLE,...,56,40,3,61.0,35.0,A2,303,NaN,46.0,PUBLICAR
1,TI,COLOMBIA,F,06/10/2004,20211,SB11202110041799,ESTUDIANTE,COLOMBIA,No,VALLE,...,61,53,3,69.0,45.0,B1,325,NaN,62.0,PUBLICAR
2,TI,COLOMBIA,F,01/10/2003,20211,SB11202110043835,ESTUDIANTE,COLOMBIA,No,VALLE,...,73,90,4,69.0,46.0,B1,374,NaN,92.0,PUBLICAR
3,TI,COLOMBIA,F,13/01/2003,20211,SB11202110043668,ESTUDIANTE,COLOMBIA,No,VALLE,...,53,32,2,60.0,33.0,A2,282,NaN,34.0,PUBLICAR
4,TI,COLOMBIA,F,29/08/2004,20211,SB11202110043350,ESTUDIANTE,COLOMBIA,No,VALLE,...,53,34,2,60.0,33.0,A2,288,NaN,38.0,PUBLICAR

df df_SB11_20212

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_DEPTO_RESIDE,...,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION,ESTU_GENERACION-E
0,TI,COLOMBIA,F,09/01/2004,20214,SB11202140617020,ESTUDIANTE,COLOMBIA,No,CALDAS,...,6.0,A-,158,2.0,NaN,48.765076,2.0,2.0,PUBLICAR,GENERACION E - GRATUIDAD
1,TI,COLOMBIA,M,06/04/2005,20214,SB11202140623058,ESTUDIANTE,COLOMBIA,No,CALDAS,...,30.0,A-,179,8.0,NaN,47.657176,2.0,2.0,PUBLICAR,NO
2,TI,COLOMBIA,F,28/03/2004,20214,SB11202140623602,ESTUDIANTE,COLOMBIA,No,CALDAS,...,29.0,A-,239,47.0,NaN,37.502857,1.0,1.0,PUBLICAR,NO
3,TI,COLOMBIA,F,28/04/2005,20214,SB11202140622167,ESTUDIANTE,COLOMBIA,No,RISARALDA,...,38.0,A-,232,42.0,NaN,44.092403,2.0,1.0,PUBLICAR,GENERACION E - GRATUIDAD
4,TI,COLOMBIA,F,16/11/2004,20214,SB11202140633564,ESTUDIANTE,COLOMBIA,No,CALDAS,...,55.0,A1,270,69.0,NaN,51.597759,3.0,2.0,PUBLICAR,GENERACION E - GRATUIDAD

df df_SB11_20221

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_DEPTO_RESIDE,...,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION,ESTU_AGREGADO
0,TI,COLOMBIA,F,04/06/2005,20221,SB11202210006203,ESTUDIANTE,COLOMBIA,No,NARIÑO,...,72,B1,349,83,NaN,71.540067,4.0,4,PUBLICAR,S
1,TI,COLOMBIA,M,09/11/2004,20221,SB11202210006838,ESTUDIANTE,COLOMBIA,No,NARIÑO,...,65,B1,362,90,NaN,75.846582,4.0,4,PUBLICAR,S
2,TI,COLOMBIA,M,09/06/2005,20221,SB11202210007358,ESTUDIANTE,COLOMBIA,No,NARIÑO,...,64,B1,333,74,NaN,72.548099,4.0,4,PUBLICAR,S
3,TI,COLOMBIA,F,12/07/2005,20221,SB11202210007741,ESTUDIANTE,COLOMBIA,No,NARIÑO,...,53,A2,342,79,NaN,81.064200,4.0,4,PUBLICAR,S
4,TI,COLOMBIA,F,21/08/2005,20221,SB11202210009435,ESTUDIANTE,COLOMBIA,No,NARIÑO,...,64,B1,308,59,NaN,71.244606,4.0,4,PUBLICAR,S

df df_SB11_20222

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_DEPTO_RESIDE,...,PUNT_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,PUNT_GLOBAL,PERCENTIL_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION
0,CC,COLOMBIA,M,10/12/2000,20224,SB11202240576111,ESTUDIANTE,COLOMBIA,Si,CASANARE,...,24,1,1,138,NaN,1.0,NaN,NaN,2.0,PUBLICAR
1,CC,COLOMBIA,M,06/12/2001,20224,SB11202240348492,ESTUDIANTE,COLOMBIA,Si,ARAUCA,...,26,1,2,142,NaN,1.0,46.850625,2.0,2.0,PUBLICAR
2,CC,COLOMBIA,M,09/08/1976,20224,SB11202240543685,ESTUDIANTE,COLOMBIA,Si,CAUCA,...,32,1,10,148,1.0,1.0,25.786828,1.0,1.0,PUBLICAR
3,CC,COLOMBIA,M,14/06/1993,20224,SB11202240543401,ESTUDIANTE,COLOMBIA,Si,CAUCA,...,24,1,1,120,1.0,1.0,NaN,NaN,1.0,PUBLICAR
4,CC,COLOMBIA,M,07/02/1976,20224,SB11202240543298,ESTUDIANTE,COLOMBIA,Si,CAUCA,...,27,1,3,110,1.0,1.0,32.523512,1.0,1.0,PUBLICAR

df df_SB11_20231

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_DEPTO_RESIDE,...,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL,ESTU_ESTADOINVESTIGACION
0,TI,COLOMBIA,M,03/11/2005,20231,SB11202310035535,ESTUDIANTE,COLOMBIA,No,VALLE,...,65,73,3,55.0,39.0,A1,315,64.0,NaN,PUBLICAR
1,TI,COLOMBIA,F,16/06/2005,20231,SB11202310033658,ESTUDIANTE,COLOMBIA,No,VALLE,...,39,17,1,43.0,16.0,A-,215,18.0,NaN,PUBLICAR
2,TI,COLOMBIA,M,30/01/2006,20231,SB11202310033771,ESTUDIANTE,COLOMBIA,No,VALLE,...,57,54,3,55.0,39.0,A1,291,52.0,NaN,PUBLICAR
3,TI,COLOMBIA,M,13/07/2006,20231,SB11202310030818,ESTUDIANTE,COLOMBIA,No,VALLE,...,51,41,2,63.0,49.0,A2,272,43.0,NaN,PUBLICAR
4,TI,COLOMBIA,M,15/01/2006,20231,SB11202310033782,ESTUDIANTE,COLOMBIA,No,VALLE,...,43,23,2,38.0,9.0,A-,218,19.0,NaN,PUBLICAR

done

-- ¿Cómo se exploran y describen las relaciones entre variables?

De la exploración de los datos, se identifica el campo ESTU_CONSECUTIVO que corresponde al identificador asignado al estudiante para la presentación de la prueba Saber11. Este campo será de utilizar para indexar las colecciones a generar.

Las variables cuantitativas correspondientes al puntajo obtenido en las pruebas, segun lo identificado en el proyecto de Machine Learning tienen relación con las siguientes variables, en donde se identificó alguna medida de correlación y por lo tanto fueron variables a considerar en el modelo de clasificación desarrollado. Estas variables corresponden a las siguientes:

* FAMI_EDUCACIONMADRE
* FAMI_EDUCACIONPADRE
* FAMI_ESTRATOVIVIENDA
* ESTU_DEDICACIONLECTURADIARIA
* FAMI_NUMLIBROS
* ESTU_DEDICACIONINTERNET
* FAMI_COMELECHEDERIVADOS
* ESTU_EDAD
* FAMI_COMECARNEPESCADOHUEVO
* FAMI_SITUACIONECONOMICA
* COLE_JORNADA
* FAMI_TIENECOMPUTADOR
* FAMI_TIENEINTERNET
* COLE_NATURALEZA
* ESTU_GENERO
* COLE_CARACTER
* COLE_CALENDARIO

En donde la variable ESTU_EDAD corresponde a una variable calculada en función de la fecha de nacimiento del estudiante y la fecha de presentación de la prueba. Esta variable no se tendra en cuenta inicialmente.

In [ ]:
# validar los dataframes antes de concatenar
columnList = []
dictDf     = {}
for name_df in list(dict_of_df.keys()):
    print("\ndf",name_df)
    df = dict_of_df[name_df]
    display(df.describe())
print("done")

df df_SB11_20171

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,DESEMP_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,12993.0,12993.000000,12993.000000,12993.000000,1.299300e+04,1.299300e+04,12993.000000,12993.000000,12993.000000,12993.000000,...,12993.000000,12993.000000,12993.000000,12993.000000,12993.000000,12993.000000,12993.000000,12993.000000,12684.000000,12957.000000
mean,20171.0,48.132995,48189.418071,61073.115447,3.573368e+11,3.573368e+11,48724.357962,48.625183,48117.165782,48.066420,...,2.972908,61.938351,62.491957,2.920111,69.901178,64.178096,314.669668,64.139460,65.742859,3.662113
std,0.0,31.137969,31159.397700,60902.468801,4.112046e+10,4.112046e+10,30698.019697,30.707827,31247.559166,31.238697,...,0.727942,11.156838,25.131623,0.769606,16.375602,23.715485,50.063350,23.720119,8.421599,0.484455
min,20171.0,5.000000,5001.000000,182.000000,1.765200e+11,1.765200e+11,5001.000000,5.000000,5001.000000,5.000000,...,1.000000,19.000000,1.000000,1.000000,13.000000,1.000000,145.000000,1.000000,27.894284,2.000000
25%,20171.0,11.000000,11001.000000,18556.000000,3.118480e+11,3.118480e+11,11001.000000,11.000000,11001.000000,11.000000,...,3.000000,55.000000,44.000000,2.000000,58.000000,47.000000,281.000000,47.000000,59.817480,3.000000
50%,20171.0,76.000000,76001.000000,42473.000000,3.760010e+11,3.760010e+11,76001.000000,76.000000,76001.000000,76.000000,...,3.000000,63.000000,66.000000,3.000000,72.000000,67.000000,319.000000,67.000000,66.417671,4.000000
75%,20171.0,76.000000,76001.000000,95216.000000,3.760010e+11,3.760010e+11,76001.000000,76.000000,76001.000000,76.000000,...,3.000000,70.000000,84.000000,3.000000,82.000000,84.000000,351.000000,84.000000,71.882050,4.000000
max,20171.0,91.000000,91001.000000,663617.000000,4.768921e+11,4.768921e+11,76892.000000,76.000000,76834.000000,76.000000,...,4.000000,100.000000,100.000000,4.000000,100.000000,100.000000,476.000000,100.000000,83.361523,4.000000

df df_SB11_20172

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,DESEMP_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,546261.0,545919.000000,545919.000000,546261.000000,5.462610e+05,5.462610e+05,546261.000000,546261.000000,546261.000000,546261.000000,...,546261.000000,546261.000000,546261.000000,546261.000000,546261.000000,546261.000000,546261.000000,546261.00000,539249.000000,545269.000000
mean,20172.0,32.975711,32661.581852,142127.810514,2.041843e+11,2.048410e+11,32681.860175,32.446389,32608.902695,32.393490,...,2.210755,50.225634,50.218685,2.151849,49.519305,50.225235,255.230419,50.05216,50.283739,2.334661
std,0.0,235.826838,26447.475610,171474.372140,9.295789e+10,9.415292e+10,26432.473908,26.405895,26481.138063,26.452665,...,0.727752,11.123840,28.885776,0.786026,11.456194,28.878187,48.483642,28.91788,9.029347,0.694732
min,20172.0,5.000000,5001.000000,18.000000,1.050010e+11,1.050010e+11,5001.000000,5.000000,5001.000000,5.000000,...,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.00000,14.413616,1.000000
25%,20172.0,11.000000,11001.000000,37499.000000,1.170130e+11,1.170420e+11,11001.000000,11.000000,11001.000000,11.000000,...,2.000000,42.000000,25.000000,2.000000,41.000000,25.000000,218.000000,25.00000,44.010248,2.000000
50%,20172.0,20.000000,20178.000000,98624.000000,1.730010e+11,1.732000e+11,20238.000000,20.000000,20013.000000,20.000000,...,2.000000,50.000000,50.000000,2.000000,48.000000,50.000000,253.000000,50.00000,49.824423,2.000000
75%,20172.0,54.000000,54001.000000,156398.000000,3.050880e+11,3.050880e+11,54001.000000,54.000000,54001.000000,54.000000,...,3.000000,58.000000,75.000000,3.000000,56.000000,75.000000,289.000000,75.00000,55.803507,3.000000
max,20172.0,99999.000000,99999.000000,711671.000000,8.548740e+11,8.548740e+11,99773.000000,99.000000,99773.000000,99.000000,...,4.000000,100.000000,100.000000,4.000000,100.000000,100.000000,476.000000,100.00000,84.394966,4.000000

df df_SB11_20181

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,DESEMP_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,12527.0,12527.000000,12527.000000,12527.000000,1.252700e+04,1.252700e+04,12527.000000,12527.000000,12527.000000,12527.000000,...,12527.000000,12527.000000,12527.000000,12527.000000,12527.000000,12527.000000,12527.000000,12527.000000,12268.000000,12430.000000
mean,20181.0,47.900535,47961.106809,89216.197014,3.577158e+11,3.576174e+11,48499.348846,48.396504,47908.273569,47.852798,...,2.971981,62.157420,63.101780,2.936298,70.508023,64.849525,319.064740,64.512174,65.850318,3.272164
std,0.0,31.099142,31119.274248,136731.527976,4.197414e+10,4.195383e+10,30631.707886,30.640298,31182.854721,31.173888,...,0.734799,11.251631,24.834225,0.789984,13.887193,23.065373,49.073217,23.400804,8.564458,0.588480
min,20181.0,5.000000,5001.000000,182.000000,1.765200e+11,1.765200e+11,5001.000000,5.000000,5001.000000,5.000000,...,1.000000,22.000000,1.000000,1.000000,0.000000,1.000000,137.000000,1.000000,21.593090,1.000000
25%,20181.0,11.000000,11001.000000,19349.000000,3.118480e+11,3.118480e+11,11001.000000,11.000000,11001.000000,11.000000,...,3.000000,55.000000,45.000000,2.000000,60.000000,48.000000,287.000000,48.000000,59.668382,3.000000
50%,20181.0,76.000000,76001.000000,46441.000000,3.760010e+11,3.760010e+11,76001.000000,76.000000,76001.000000,76.000000,...,3.000000,63.000000,66.000000,3.000000,73.000000,67.000000,326.000000,67.000000,66.417091,3.000000
75%,20181.0,76.000000,76001.000000,106120.000000,3.760010e+11,3.760010e+11,76001.000000,76.000000,76001.000000,76.000000,...,3.000000,70.000000,84.000000,3.000000,82.000000,84.000000,355.000000,84.000000,72.101129,4.000000
max,20181.0,76.000000,76895.000000,714634.000000,4.768921e+11,4.768921e+11,76892.000000,76.000000,76834.000000,76.000000,...,4.000000,100.000000,100.000000,4.000000,100.000000,100.000000,475.000000,100.000000,83.580349,4.000000

df df_SB11_20182

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,DESEMP_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_INSE_INDIVIDUAL
count,549934.0,549798.000000,549798.000000,549934.000000,5.499340e+05,5.499340e+05,549934.000000,549934.000000,549934.000000,549934.000000,...,549934.000000,549934.000000,549934.000000,549934.000000,549913.000000,549934.000000,549934.000000,549934.000000,549357.000000,531707.000000
mean,20182.0,32.629602,32683.301269,162955.208005,2.036651e+11,2.042115e+11,32715.352964,32.479376,32628.753490,32.412273,...,2.097163,48.192112,50.192330,2.017415,50.602090,50.141171,250.775497,50.019439,2.366183,49.950951
std,0.0,137.381937,26437.045068,196626.819524,9.275065e+10,9.343486e+10,26419.705220,26.392924,26466.959458,26.439035,...,0.754253,11.779078,28.909308,0.821984,11.532563,28.903653,50.089846,28.964273,0.660183,9.746965
min,20182.0,5.000000,5001.000000,18.000000,1.050010e+11,1.050010e+11,5001.000000,5.000000,5001.000000,5.000000,...,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,12.538867
25%,20182.0,11.000000,11001.000000,40899.000000,1.170010e+11,1.170130e+11,11001.000000,11.000000,11001.000000,11.000000,...,2.000000,39.000000,25.000000,1.000000,42.000000,25.000000,212.000000,25.000000,2.000000,43.048188
50%,20182.0,20.000000,20250.000000,103762.000000,1.730300e+11,1.732680e+11,20400.000000,20.000000,20060.000000,20.000000,...,2.000000,47.000000,50.000000,2.000000,49.000000,50.000000,247.000000,50.000000,2.000000,49.590000
75%,20182.0,54.000000,54001.000000,166454.000000,3.050010e+11,3.050010e+11,54001.000000,54.000000,54001.000000,54.000000,...,3.000000,57.000000,75.000000,3.000000,57.000000,75.000000,286.000000,75.000000,3.000000,56.179959
max,20182.0,99999.000000,99999.000000,720151.000000,8.548740e+11,8.548740e+11,99773.000000,99.000000,99773.000000,99.000000,...,4.000000,100.000000,100.000000,4.000000,100.000000,100.000000,478.000000,100.000000,4.000000,84.836366

df df_SB11_20191

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,21083.0,21066.000000,21066.000000,21083.000000,2.108300e+04,2.108300e+04,21083.000000,21083.000000,21083.000000,21083.000000,...,21083.000000,21083.000000,21083.000000,21083.000000,21083.000000,21083.000000,21083.000000,20237.000000,20237.000000,21079.000000
mean,20191.0,40.426944,40518.620763,141797.042878,3.396811e+11,3.396594e+11,40756.556040,40.640753,40150.537447,40.076555,...,54.217711,50.542285,2.420196,60.424513,50.531993,281.569890,50.438363,60.953848,3.150615,3.164666
std,0.0,30.408437,30422.285334,182708.938647,5.830963e+10,5.829908e+10,30272.310175,30.270985,30529.522062,30.520113,...,14.530059,28.879391,0.984282,18.362115,28.887185,66.183667,28.886206,12.028776,0.900542,0.815434
min,20191.0,5.000000,5001.000000,182.000000,1.050010e+11,1.050010e+11,5001.000000,5.000000,5001.000000,5.000000,...,17.000000,1.000000,1.000000,0.000000,1.000000,68.000000,1.000000,16.027618,1.000000,1.000000
25%,20191.0,11.000000,11001.000000,31369.000000,3.110011e+11,3.110011e+11,11001.000000,11.000000,11001.000000,11.000000,...,42.000000,26.000000,2.000000,45.000000,26.000000,226.000000,25.000000,52.359444,3.000000,3.000000
50%,20191.0,25.000000,25307.000000,94250.000000,3.410010e+11,3.410010e+11,25377.000000,25.000000,25307.000000,25.000000,...,55.000000,51.000000,2.000000,61.000000,51.000000,286.000000,51.000000,61.598530,3.000000,3.000000
75%,20191.0,76.000000,76001.000000,155036.000000,3.760010e+11,3.760010e+11,76001.000000,76.000000,76001.000000,76.000000,...,66.000000,76.000000,3.000000,77.000000,76.000000,337.000000,75.000000,70.464218,4.000000,4.000000
max,20191.0,99.000000,99001.000000,721647.000000,6.252690e+11,6.252690e+11,95001.000000,95.000000,99001.000000,99.000000,...,100.000000,100.000000,4.000000,100.000000,100.000000,470.000000,100.000000,84.836365,4.000000,4.000000

df df_SB11_20192

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,546212.0,545835.000000,545835.000000,546212.000000,5.462120e+05,5.462120e+05,546212.000000,546212.000000,546212.000000,546212.000000,...,546212.000000,546212.000000,546212.000000,546193.000000,546212.000000,546212.000000,546193.000000,529167.000000,529167.000000,546168.000000
mean,20194.0,57.025856,32739.615413,197397.840712,2.038424e+11,2.044208e+11,32755.704584,32.516563,32723.924917,32.503804,...,46.224589,50.179648,1.901584,48.416891,50.098669,246.186464,49.994324,50.218395,2.352263,2.376862
std,0.0,1566.335590,26397.937526,229636.502160,9.221826e+10,9.302404e+10,26364.009436,26.340054,26425.441138,26.399203,...,12.140588,28.911682,0.820178,12.558438,28.917401,51.386858,28.976534,9.721808,0.866252,0.686206
min,20194.0,5.000000,5001.000000,75.000000,1.050010e+11,1.050010e+11,5001.000000,5.000000,5001.000000,5.000000,...,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,14.593814,1.000000,1.000000
25%,20194.0,11.000000,11001.000000,45732.000000,1.170500e+11,1.171740e+11,11001.000000,11.000000,11001.000000,11.000000,...,37.000000,25.000000,1.000000,39.000000,25.000000,207.000000,25.000000,43.325031,2.000000,2.000000
50%,20194.0,20.000000,20570.000000,113076.000000,1.732085e+11,1.733190e+11,20750.000000,20.000000,20250.000000,20.000000,...,45.000000,50.000000,2.000000,48.000000,50.000000,243.000000,50.000000,49.877138,2.000000,2.000000
75%,20194.0,54.000000,54001.000000,194779.000000,3.050010e+11,3.050010e+11,54001.000000,54.000000,54001.000000,54.000000,...,55.000000,75.000000,2.000000,56.000000,75.000000,282.000000,75.000000,56.488433,3.000000,3.000000
max,20194.0,99999.000000,99999.000000,728303.000000,8.548740e+11,8.548740e+11,99773.000000,99.000000,99773.000000,99.000000,...,100.000000,100.000000,4.000000,100.000000,100.000000,477.000000,100.000000,84.836366,4.000000,4.000000

df df_SB11_20201

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,15435.0,14671.000000,14671.000000,15435.000000,1.543500e+04,1.543500e+04,15435.00000,15435.000000,15435.000000,15435.000000,...,15435.000000,15435.000000,15435.000000,15399.000000,15435.000000,15435.000000,15399.000000,14744.000000,14744.000000,15430.000000
mean,20201.0,44.351578,44437.509713,130832.516553,3.497608e+11,3.498385e+11,44475.56482,44.366893,43952.395724,43.880143,...,55.223000,50.292906,2.496016,64.948633,50.427600,289.434338,50.269238,63.431363,3.339867,3.382566
std,0.0,30.620482,30630.074031,178352.159641,4.683646e+10,4.704429e+10,30386.87119,30.391557,30814.768289,30.808170,...,13.792992,28.903069,0.936444,17.863339,29.177412,60.299185,28.886154,10.782124,0.782963,0.694912
min,20201.0,5.000000,5001.000000,182.000000,1.050450e+11,1.050450e+11,5001.00000,5.000000,5001.000000,5.000000,...,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,20.054037,1.000000,1.000000
25%,20201.0,11.000000,11001.000000,24299.000000,3.117690e+11,3.117690e+11,11001.00000,11.000000,11001.000000,11.000000,...,45.000000,25.000000,2.000000,52.000000,25.000000,245.000000,25.000000,56.239507,3.000000,3.000000
50%,20201.0,52.000000,52001.000000,79327.000000,3.660010e+11,3.680010e+11,52001.00000,52.000000,52001.000000,52.000000,...,57.000000,50.000000,3.000000,67.000000,50.000000,295.000000,50.000000,64.248087,4.000000,3.000000
75%,20201.0,76.000000,76001.000000,135574.000000,3.760010e+11,3.760010e+11,76001.00000,76.000000,76001.000000,76.000000,...,66.000000,75.000000,3.000000,78.000000,75.000000,336.000000,75.000000,71.453861,4.000000,4.000000
max,20201.0,94.000000,94001.000000,730416.000000,5.190010e+11,6.252690e+11,86320.00000,86.000000,94001.000000,94.000000,...,100.000000,100.000000,4.000000,100.000000,100.000000,479.000000,100.000000,84.836366,4.000000,4.000000

df df_SB11_20202

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,504872.0,504870.000000,504870.000000,504872.000000,5.048720e+05,5.048720e+05,504872.000000,504872.000000,504664.000000,504664.000000,...,504872.000000,504872.000000,504872.000000,504538.000000,504872.000000,504872.000000,504872.000000,490927.000000,490927.000000,504823.000000
mean,20204.0,36.099671,32579.046941,291073.583621,2.013835e+11,2.017896e+11,32557.154356,32.317999,32580.469552,32.358585,...,48.233939,50.238106,2.020696,46.883507,50.123681,248.347102,50.097839,50.809918,2.406900,2.428802
std,0.0,613.810991,26367.519505,289443.194840,9.096065e+10,9.151341e+10,26337.925906,26.312655,26408.566261,26.382008,...,11.970584,28.889352,0.825769,11.313128,28.927940,48.692523,28.903895,9.444813,0.846049,0.661466
min,20204.0,5.000000,5001.000000,83.000000,1.050010e+11,1.050010e+11,5001.000000,5.000000,5001.000000,5.000000,...,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,14.281577,1.000000,1.000000
25%,20204.0,11.000000,11001.000000,60343.000000,1.158350e+11,1.158610e+11,11001.000000,11.000000,11001.000000,11.000000,...,39.000000,25.000000,1.000000,39.000000,25.000000,211.000000,25.000000,44.314347,2.000000,2.000000
50%,20204.0,20.000000,20400.000000,141838.000000,1.730010e+11,1.730010e+11,20443.000000,20.000000,20238.000000,20.000000,...,47.000000,50.000000,2.000000,45.000000,50.000000,245.000000,50.000000,50.633782,2.000000,2.000000
75%,20204.0,54.000000,54001.000000,669267.000000,3.050010e+11,3.050010e+11,54001.000000,54.000000,54001.000000,54.000000,...,57.000000,75.000000,3.000000,52.000000,75.000000,282.000000,75.000000,56.832224,3.000000,3.000000
max,20204.0,99999.000000,99999.000000,752444.000000,8.548740e+11,8.548740e+11,99773.000000,99.000000,99773.000000,99.000000,...,100.000000,100.000000,4.000000,100.000000,100.000000,500.000000,100.000000,84.836366,4.000000,4.000000

df df_SB11_20211

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,PERCENTIL_C_NATURALES,DESEMP_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL,PERCENTIL_GLOBAL
count,15528.0,15520.000000,15520.000000,15528.000000,1.552800e+04,1.552800e+04,15528.000000,15528.000000,15528.000000,15528.000000,...,15528.000000,15528.000000,15528.000000,15528.000000,15528.000000,15481.000000,15481.000000,15528.000000,155.000000,15481.000000
mean,20211.0,45.747809,45829.474936,145880.321162,3.544931e+11,3.549761e+11,46269.042117,46.155848,45703.637944,45.632535,...,50.346793,2.659776,58.145093,50.340160,2.674652,68.414637,50.538144,301.820325,54.645161,50.319488
std,0.0,30.774033,30793.339571,210187.618713,4.568720e+10,4.788891e+10,30438.263098,30.441098,30909.375642,30.903677,...,28.883524,0.797352,13.017355,28.880826,0.885335,16.989953,28.970527,57.620860,28.864381,28.842544
min,20211.0,5.000000,5001.000000,182.000000,1.050010e+11,1.050010e+11,5001.000000,5.000000,5001.000000,5.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,22.000000,10.000000,1.000000
25%,20211.0,11.000000,11001.000000,21899.000000,3.118480e+11,3.118480e+11,11001.000000,11.000000,11001.000000,11.000000,...,25.000000,2.000000,50.000000,25.000000,2.000000,56.000000,25.000000,263.000000,30.000000,25.000000
50%,20211.0,52.000000,52356.000000,70086.000000,3.760010e+11,3.760010e+11,52356.000000,52.000000,52356.000000,52.000000,...,50.000000,3.000000,60.000000,50.000000,3.000000,72.000000,50.000000,309.000000,60.000000,50.000000
75%,20211.0,76.000000,76001.000000,136127.000000,3.760010e+11,3.760010e+11,76001.000000,76.000000,76001.000000,76.000000,...,75.000000,3.000000,68.000000,75.000000,3.000000,82.000000,75.000000,345.000000,80.000000,75.000000
max,20211.0,95.000000,95001.000000,752717.000000,5.190010e+11,8.180011e+11,95001.000000,95.000000,95001.000000,95.000000,...,100.000000,4.000000,100.000000,100.000000,4.000000,100.000000,100.000000,495.000000,100.000000,100.000000

df df_SB11_20212

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,532979.0,532902.000000,532902.000000,532979.000000,5.329790e+05,5.329790e+05,532979.000000,532979.000000,532979.00000,532979.000000,...,532979.000000,532979.000000,529094.000000,529094.000000,532979.000000,529094.000000,15437.000000,517816.000000,517816.000000,532912.000000
mean,20214.0,40.943012,32935.709378,299822.163930,2.014601e+11,2.020027e+11,32925.664525,32.684010,32934.59592,32.710249,...,50.027543,1.937956,48.982016,50.146012,246.024008,50.020410,50.283928,50.632586,2.393377,2.414337
std,0.0,908.702925,26414.288147,292813.541513,9.025118e+10,9.086518e+10,26389.618703,26.365685,26449.15459,26.423223,...,28.921342,0.813229,12.845504,28.878263,50.623078,28.935729,28.882637,9.377702,0.841577,0.654466
min,20214.0,5.000000,5001.000000,83.000000,1.050010e+11,1.050010e+11,5001.000000,5.000000,5001.00000,5.000000,...,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,12.717100,1.000000,1.000000
25%,20214.0,11.000000,11001.000000,62521.000000,1.170010e+11,1.170010e+11,11001.000000,11.000000,11001.00000,11.000000,...,25.000000,1.000000,39.000000,25.000000,207.000000,25.000000,25.000000,44.197712,2.000000,2.000000
50%,20214.0,23.000000,23001.000000,144998.000000,1.730010e+11,1.730010e+11,23001.000000,23.000000,23001.00000,23.000000,...,50.000000,2.000000,48.000000,50.000000,242.000000,50.000000,50.000000,50.410960,2.000000,2.000000
75%,20214.0,54.000000,54001.000000,694190.000000,3.050010e+11,3.050010e+11,54001.000000,54.000000,54001.00000,54.000000,...,75.000000,3.000000,57.000000,75.000000,281.000000,75.000000,75.000000,56.578354,3.000000,3.000000
max,20214.0,99999.000000,99999.000000,759365.000000,5.523990e+11,8.548740e+11,99773.000000,99.000000,99773.00000,99.000000,...,100.000000,4.000000,100.000000,100.000000,494.000000,100.000000,100.000000,84.836366,4.000000,4.000000

df df_SB11_20221

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,12859.0,12857.000000,12857.000000,12859.000000,1.285900e+04,1.285900e+04,12859.000000,12859.000000,12859.000000,12859.000000,...,12859.000000,12859.000000,12859.000000,12859.000000,12859.000000,12859.000000,12.00000,12400.000000,12400.000000,12859.000000
mean,20221.0,47.541262,47615.475461,138949.019131,3.587525e+11,3.587525e+11,47903.525624,47.786609,47444.208026,47.385178,...,62.755813,2.829536,72.081966,64.595458,315.322731,64.215102,95.00000,69.057548,3.728629,3.760401
std,0.0,31.039743,31062.543281,214579.552109,4.242649e+10,4.242649e+10,30724.393934,30.736129,31191.833550,31.183082,...,24.886345,0.802195,14.156728,23.258089,47.706508,23.428338,9.04534,7.278168,0.450809,0.426855
min,20221.0,5.000000,5001.000000,182.000000,1.765200e+11,1.765200e+11,5001.000000,5.000000,5001.000000,5.000000,...,1.000000,1.000000,0.000000,1.000000,100.000000,1.000000,70.00000,44.975714,2.000000,3.000000
25%,20221.0,11.000000,11001.000000,19497.000000,3.118480e+11,3.118480e+11,11001.000000,11.000000,11001.000000,11.000000,...,45.000000,2.000000,62.000000,48.000000,285.000000,47.000000,90.00000,63.612929,3.000000,4.000000
50%,20221.0,76.000000,76001.000000,54528.000000,3.760010e+11,3.760010e+11,76001.000000,76.000000,76001.000000,76.000000,...,66.000000,3.000000,75.000000,67.000000,321.000000,67.000000,100.00000,69.319127,4.000000,4.000000
75%,20221.0,76.000000,76001.000000,124032.000000,3.760010e+11,3.760010e+11,76001.000000,76.000000,76001.000000,76.000000,...,84.000000,3.000000,82.000000,84.000000,350.000000,84.000000,100.00000,74.246972,4.000000,4.000000
max,20221.0,85.000000,85440.000000,780247.000000,4.768921e+11,4.768921e+11,76892.000000,76.000000,85001.000000,85.000000,...,100.000000,4.000000,100.000000,100.000000,476.000000,100.000000,100.00000,84.836366,4.000000,4.000000

df df_SB11_20222

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_COD_DANE_ESTABLECIMIENTO,COLE_CODIGO_ICFES,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,ESTU_COD_DEPTO_PRESENTACION,...,PERCENTIL_LECTURA_CRITICA,PUNT_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,PUNT_GLOBAL,PERCENTIL_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
count,532792.0,532791.000000,532791.000000,5.327910e+05,532791.000000,5.327910e+05,532791.000000,532791.000000,532792.000000,532792.000000,...,532792.000000,532792.000000,532792.000000,532792.000000,532792.000000,530815.000000,9700.000000,509685.000000,509685.000000,532718.000000
mean,20224.0,32.925849,32982.304780,2.024764e+11,312550.105402,2.029818e+11,33001.209088,32.756633,33003.681373,32.776879,...,50.125801,47.702850,1.989810,50.202319,250.138467,50.120332,50.225155,50.270136,2.360103,2.377682
std,0.0,139.476060,26427.119229,9.072786e+10,297220.547271,9.125292e+10,26413.315478,26.389978,26475.768591,26.450210,...,28.933084,11.923581,0.822736,28.893839,51.837475,28.929757,28.862188,9.416406,0.844597,0.643857
min,20224.0,5.000000,5001.000000,1.050010e+11,83.000000,1.050010e+11,5001.000000,5.000000,5001.000000,5.000000,...,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,12.717100,1.000000,1.000000
25%,20224.0,11.000000,11001.000000,1.170690e+11,67298.000000,1.171740e+11,11001.000000,11.000000,11001.000000,11.000000,...,25.000000,38.000000,1.000000,25.000000,210.000000,25.000000,25.000000,43.800700,2.000000,2.000000
50%,20224.0,23.000000,23001.000000,1.731680e+11,152496.000000,1.733190e+11,23001.000000,23.000000,23001.000000,23.000000,...,50.000000,47.000000,2.000000,50.000000,247.000000,50.000000,50.000000,49.909106,2.000000,2.000000
75%,20224.0,54.000000,54001.000000,3.050010e+11,708768.000000,3.050010e+11,54001.000000,54.000000,54001.000000,54.000000,...,75.000000,57.000000,3.000000,75.000000,288.000000,75.000000,75.000000,56.227217,3.000000,3.000000
max,20224.0,99999.000000,99999.000000,5.684320e+11,807305.000000,8.180011e+11,99773.000000,99.000000,99773.000000,99.000000,...,100.000000,100.000000,4.000000,100.000000,477.000000,100.000000,100.000000,84.836366,4.000000,4.000000

df df_SB11_20231

,PERIODO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,SEED_CODIGOMEN,COLE_COD_DANE_SEDE,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,ESTU_COD_MCPIO_PRESENTACION,...,PERCENTIL_C_NATURALES,DESEMP_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,PERCENTIL_ESPECIAL_GLOBAL
count,12704.0,12704.000000,12704.000000,12704.000000,1.270400e+04,12704.000000,1.270400e+04,12704.000000,12704.000000,12704.000000,...,12704.000000,12704.000000,12704.000000,12704.00000,12704.000000,12702.000000,12702.000000,12704.000000,12702.000000,11.000000
mean,20231.0,46.861067,46930.803999,137812.243545,3.580633e+11,144.347607,3.580633e+11,47219.970954,47.107761,46800.813996,...,64.831707,2.862327,60.825882,64.00063,2.851464,72.882066,65.866635,316.850362,65.505196,88.000000
std,0.0,31.060190,31076.671884,212074.542023,4.236889e+10,62.767199,4.236889e+10,30787.343950,30.801400,31190.814381,...,23.814560,0.739364,11.093112,24.36030,0.786343,13.992488,22.735517,48.062085,22.852094,19.879638
min,20231.0,5.000000,5001.000000,182.000000,1.765200e+11,5.000000,1.765200e+11,5001.000000,5.000000,5001.000000,...,1.000000,1.000000,24.000000,1.00000,1.000000,26.000000,1.000000,140.000000,1.000000,40.000000
25%,20231.0,11.000000,11001.000000,19497.000000,3.118480e+11,68.000000,3.118480e+11,11001.000000,11.000000,11001.000000,...,48.000000,2.000000,54.000000,47.00000,2.000000,63.000000,50.000000,286.750000,49.000000,92.500000
50%,20231.0,68.000000,68276.000000,55657.000000,3.760010e+11,188.000000,3.760010e+11,68276.000000,68.000000,68001.000000,...,68.000000,3.000000,62.000000,67.00000,3.000000,76.000000,68.000000,323.000000,68.000000,97.000000
75%,20231.0,76.000000,76001.000000,124032.000000,3.760010e+11,188.000000,3.760010e+11,76001.000000,76.000000,76001.000000,...,85.000000,3.000000,69.000000,84.00000,3.000000,82.000000,85.000000,352.000000,85.000000,98.500000
max,20231.0,81.000000,81001.000000,809145.000000,4.768921e+11,272.000000,4.768921e+11,76892.000000,76.000000,81001.000000,...,100.000000,4.000000,100.000000,100.00000,4.000000,100.000000,100.000000,478.000000,100.000000,100.000000

done

Se observa en las anteriores estadísticas que hay variables numéricas en el dataset que realmente corresponden a códigos (Ej. ESTU_COD_RESIDE_DEPTO, COLE_CODIGO_ICFES), las cuales no brindan información a nivel estadístico, pero nos podrán ser de utilidad para efectos de variables de agrupación para generacion de estadísticas sobre las variables correspondientes al resultado obtenidos en las pruebas.

## **3. Carga o Adquisición de Datos**
---

Agregue el código necesario en _Python_ para obtener o cargar los datos.

### **3.1. Origen de los datos**
---
- ¿Cuál es la fuente principal de los datos?

Como se ha mencionado, el dataset a analizar ha sido descargado desde la página oficial del ICFES (https://www.icfes.gov.co/web/guest/data-icfes). Corresponde a los resultados del examen Saber11 entre los años 2017 y 2023.

- ¿Existen consideraciones especiales al extraer datos de esta fuente?

No se tienen consideraciones especiales para la extracción de los datos de la fuente

- ¿Cómo se obtienen los datos del origen a la plataforma de Big Data?

Para efectos de la definicion de la arquitectura de soporte de los datos para Big Data, se utilizará la base de datos orientada a documentos MongoDB.

Al revisar los datos, no todos se aprecian de interés para el proyecto. Para los considerados, se organizaron en colecciones de la siguiente forma:
    
-- Colección icfes_estudiante_estudiante:

<img src="https://drive.google.com/uc?export=view&id=111wmkhAf4CLo0K7m7KDrpB_JXj_H1aa1" width="50%">

-- Colección icfes_estudiante_colegio:

<img src="https://drive.google.com/uc?export=view&id=1HnhBxQPhiFTVcSpXRH0RRMvU0cK6H5Nw" width="50%">

-- Colección icfes_estudiante_familia:

<img src="https://drive.google.com/uc?export=view&id=1MzyS3ziH1qm04TSr_2cUIjQLkAAOgylF" width="70%">

Para facilitar la generación de estadísticas, los datos correspondientes al puntaje en las diferentes pruebas se incluye como un nodo anidado en cada uno de los tipos de datos.

- ¿Se utilizan herramientas específicas?

Se utilizan las librerias pymongo y pymongoarrow con el fin de realizar el cargue de los datos en la base de datos

A continuación se incluye el código mediante el cual se crearan las colecciones según la estructura presentada en el numeral anterior y se procedera a realizar el cargue de los documentos correspondientes.

In [ ]:
# INGRESE SU CÓDIGO
from pymongo import MongoClient
import json

In [ ]:
# definir la conexion al servidor de la base de datos
connection_str = "mongodb://localhost:27017/"
client = MongoClient(connection_str)

In [ ]:
# definir la base de datos a trabajar
db = client["icfes_db_mlds"]
print(db)

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'icfes_db_mlds')

In [ ]:
def create_collection(collection, db):
    """"
    Función create_collection: Permite borrar y crear una colección en la base de datos

    Parámetros:
        collection   (string): Nombre de la colección a crear. Si existe previamente es borrada previo a la creación
        df (Database MongoDB): Identificador de la base de datos

    Return:
        collection (Collection MongoDB): Identificador de la colección creada en la base de datos

    Ejemplo:

        >>> icfes_estudiante_resultado  = create_collection("icfes_estudiante_resultado", db)

            *** creating collection icfes_estudiante_resultado
            done
    """
    print("*** creating collection", collection)
    db.drop_collection(collection)
    collection = db[collection]
    print("done")
    return collection

In [ ]:
def load_collection(df, collection, columns, db):
    """"
    Función load_collection: Realiza la inserción de documentos en la colección que se indica a partir de un DataFrame Pandas

    Parámetros:
        df                  (Dataframe): Nombre del Dataframe con los datos a insertar como documentos en la colección
        collection (Collection MongoDB): Nombre de la colección sobre la cual se realizará la carga de los documentos
        columns                  (List): Lista de columnas a extraer del dataframe de entrada para generar los documentos a cargar en la colección
        db           (Database MongoDB): Identificador de la base de datos

    Return:
        None

    Ejemplo:

        >>> load_collection(dict_of_df[name_df], icfes_estudiante_resultado, columns, db)

            *** loading collection Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'icfes_db_mlds')
            , 'icfes_estudiante_resultado')
            done
    """
    print("*** loading collection", collection)
    df_tmp = df[columns]
    df_tmp.reset_index(inplace=True)
    data_dict = df_tmp.to_dict("records")
    collection.insert_many(data_dict)
    print("done")
    return None

In [ ]:
def prepare_list(keys_cols, keys, keys_target, df, nested_node_name):
    """"
    Función prepare_list: Prepara lista de documentos para insertarlos en la base de datos

    Parámetros:
        keys_cols          (List): Lista de atributos a generar en el documento
        keys               (List): Lista de atributos a generar en el nodo principal del documento
        keys_target        (List): Lista de atributos a generar en el nodo anidado del documento
        df            (Dataframe): Dataframe con los datos
        nested_node_name (String): Nombre del nodo donde se depositaran los atributos anidados

    Return:
        mylist             (List): Lista de documentos a insertar en la colección

    Ejemplo:

        >>> mylist = prepare_list(keys_cols = keys_cols, keys = keys, keys_target = keys_target, df = dict_of_df[name_df], nested_node_name = 'PUNTAJE')
    """
    mydict = {}
    len_keys_cols = len(keys_cols) + 1
    for row in df[keys_cols].itertuples(index=False):
        for i in range(len(keys),len(keys_cols)):
            mydict.setdefault(row[:len_keys_cols], {})[keys_cols[i]] = row[i]

    mylist = [{**dict(zip(keys, k)), nested_node_name: v} for k, v in mydict.items()]
    return mylist

In [ ]:
icfes_estudiante_familia    = create_collection("icfes_estudiante_familia", db)
icfes_estudiante_estudiante = create_collection("icfes_estudiante_estudiante", db)
icfes_estudiante_colegio    = create_collection("icfes_estudiante_colegio", db)

*** creating collection icfes_estudiante_familia
done
*** creating collection icfes_estudiante_estudiante
done
*** creating collection icfes_estudiante_colegio
done

In [ ]:
# procesar los dataframes
ind = 1
for name_df in list(dict_of_df.keys()):
    #
    print("**** processing dataframe",name_df)
    #
    keys_cols = ['ESTU_CONSECUTIVO','FAMI_EDUCACIONPADRE','FAMI_EDUCACIONMADRE','FAMI_ESTRATOVIVIENDA','FAMI_PERSONASHOGAR','FAMI_CUARTOSHOGAR'
           ,'FAMI_TIENEINTERNET','FAMI_TIENECOMPUTADOR','FAMI_TIENELAVADORA','FAMI_TIENEHORNOMICROOGAS','FAMI_TIENESERVICIOTV'
           ,'FAMI_TIENEAUTOMOVIL','FAMI_TIENEMOTOCICLETA','FAMI_TIENECONSOLAVIDEOJUEGOS','FAMI_NUMLIBROS','FAMI_COMELECHEDERIVADOS'
           ,'FAMI_COMECARNEPESCADOHUEVO','FAMI_COMECEREALFRUTOSLEGUMBRE','FAMI_TRABAJOLABORPADRE','FAMI_TRABAJOLABORMADRE'
           ,'FAMI_SITUACIONECONOMICA'
           ,'PUNT_LECTURA_CRITICA','PUNT_MATEMATICAS'
           ,'PUNT_C_NATURALES','PUNT_SOCIALES_CIUDADANAS','PUNT_INGLES','PUNT_GLOBAL']
    keys = ['ESTU_CONSECUTIVO','FAMI_EDUCACIONPADRE','FAMI_EDUCACIONMADRE','FAMI_ESTRATOVIVIENDA','FAMI_PERSONASHOGAR','FAMI_CUARTOSHOGAR'
           ,'FAMI_TIENEINTERNET','FAMI_TIENECOMPUTADOR','FAMI_TIENELAVADORA','FAMI_TIENEHORNOMICROOGAS','FAMI_TIENESERVICIOTV'
           ,'FAMI_TIENEAUTOMOVIL','FAMI_TIENEMOTOCICLETA','FAMI_TIENECONSOLAVIDEOJUEGOS','FAMI_NUMLIBROS','FAMI_COMELECHEDERIVADOS'
           ,'FAMI_COMECARNEPESCADOHUEVO','FAMI_COMECEREALFRUTOSLEGUMBRE','FAMI_TRABAJOLABORPADRE','FAMI_TRABAJOLABORMADRE'
           ,'FAMI_SITUACIONECONOMICA']
    keys_target = ['PUNT_LECTURA_CRITICA','PUNT_MATEMATICAS','PUNT_C_NATURALES','PUNT_SOCIALES_CIUDADANAS','PUNT_INGLES','PUNT_GLOBAL']
    #
    mylist = prepare_list(keys_cols = keys_cols, keys = keys, keys_target = keys_target, df = dict_of_df[name_df], nested_node_name = 'PUNTAJE')
    icfes_estudiante_familia.insert_many(mylist)
    #
    keys_cols = ['ESTU_CONSECUTIVO','ESTU_TIPODOCUMENTO','ESTU_NACIONALIDAD','ESTU_GENERO','ESTU_FECHANACIMIENTO','PERIODO','ESTU_PAIS_RESIDE'
           ,'ESTU_TIENEETNIA','ESTU_DEPTO_RESIDE','ESTU_COD_RESIDE_DEPTO','ESTU_MCPIO_RESIDE','ESTU_COD_RESIDE_MCPIO'
           ,'ESTU_DEDICACIONLECTURADIARIA','ESTU_DEDICACIONINTERNET','ESTU_HORASSEMANATRABAJA','ESTU_TIPOREMUNERACION','ESTU_PRIVADO_LIBERTAD'
           ,'ESTU_COD_MCPIO_PRESENTACION','ESTU_MCPIO_PRESENTACION','ESTU_DEPTO_PRESENTACION','ESTU_COD_DEPTO_PRESENTACION'
           ,'PUNT_LECTURA_CRITICA','PUNT_MATEMATICAS'
           ,'PUNT_C_NATURALES','PUNT_SOCIALES_CIUDADANAS','PUNT_INGLES','PUNT_GLOBAL']
    keys = ['ESTU_CONSECUTIVO','ESTU_TIPODOCUMENTO','ESTU_NACIONALIDAD','ESTU_GENERO','ESTU_FECHANACIMIENTO','PERIODO','ESTU_PAIS_RESIDE'
           ,'ESTU_TIENEETNIA','ESTU_DEPTO_RESIDE','ESTU_COD_RESIDE_DEPTO','ESTU_MCPIO_RESIDE','ESTU_COD_RESIDE_MCPIO'
           ,'ESTU_DEDICACIONLECTURADIARIA','ESTU_DEDICACIONINTERNET','ESTU_HORASSEMANATRABAJA','ESTU_TIPOREMUNERACION','ESTU_PRIVADO_LIBERTAD'
           ,'ESTU_COD_MCPIO_PRESENTACION','ESTU_MCPIO_PRESENTACION','ESTU_DEPTO_PRESENTACION','ESTU_COD_DEPTO_PRESENTACION']
    keys_target = ['PUNT_LECTURA_CRITICA','PUNT_MATEMATICAS','PUNT_C_NATURALES','PUNT_SOCIALES_CIUDADANAS','PUNT_INGLES','PUNT_GLOBAL']
    #
    mylist = prepare_list(keys_cols = keys_cols, keys = keys, keys_target = keys_target, df = dict_of_df[name_df], nested_node_name = 'PUNTAJE')
    icfes_estudiante_estudiante.insert_many(mylist)
    #
    keys_cols = ['ESTU_CONSECUTIVO','COLE_CODIGO_ICFES','COLE_COD_DANE_ESTABLECIMIENTO','COLE_NOMBRE_ESTABLECIMIENTO','COLE_GENERO'
           ,'COLE_NATURALEZA','COLE_CALENDARIO','COLE_BILINGUE','COLE_CARACTER','COLE_COD_DANE_SEDE','COLE_NOMBRE_SEDE'
           ,'COLE_SEDE_PRINCIPAL','COLE_AREA_UBICACION','COLE_JORNADA','COLE_COD_MCPIO_UBICACION','COLE_MCPIO_UBICACION'
           ,'COLE_COD_DEPTO_UBICACION','COLE_DEPTO_UBICACION'
           ,'PUNT_LECTURA_CRITICA','PUNT_MATEMATICAS'
           ,'PUNT_C_NATURALES','PUNT_SOCIALES_CIUDADANAS','PUNT_INGLES','PUNT_GLOBAL']
    keys = ['ESTU_CONSECUTIVO','COLE_CODIGO_ICFES','COLE_COD_DANE_ESTABLECIMIENTO','COLE_NOMBRE_ESTABLECIMIENTO','COLE_GENERO'
           ,'COLE_NATURALEZA','COLE_CALENDARIO','COLE_BILINGUE','COLE_CARACTER','COLE_COD_DANE_SEDE','COLE_NOMBRE_SEDE'
           ,'COLE_SEDE_PRINCIPAL','COLE_AREA_UBICACION','COLE_JORNADA','COLE_COD_MCPIO_UBICACION','COLE_MCPIO_UBICACION'
           ,'COLE_COD_DEPTO_UBICACION','COLE_DEPTO_UBICACION']
    keys_target = ['PUNT_LECTURA_CRITICA','PUNT_MATEMATICAS','PUNT_C_NATURALES','PUNT_SOCIALES_CIUDADANAS','PUNT_INGLES','PUNT_GLOBAL']
    #
    mylist = prepare_list(keys_cols = keys_cols, keys = keys, keys_target = keys_target, df = dict_of_df[name_df], nested_node_name = 'PUNTAJE')
    icfes_estudiante_colegio.insert_many(mylist)
    #
print("done")

**** processing dataframe df_SB11_20171
**** processing dataframe df_SB11_20172
**** processing dataframe df_SB11_20181
**** processing dataframe df_SB11_20182
**** processing dataframe df_SB11_20191
**** processing dataframe df_SB11_20192
**** processing dataframe df_SB11_20201
**** processing dataframe df_SB11_20202
**** processing dataframe df_SB11_20211
**** processing dataframe df_SB11_20212
**** processing dataframe df_SB11_20221
**** processing dataframe df_SB11_20222
**** processing dataframe df_SB11_20231
done

Como complemento a los datos, realizaremos la creación de una colección correspondiente a la relación de instituciones educativas de la ciudad de Bogotá. Esta colección nos permitirá conocer la distribución de los puntajes de la prueba Saber11 en las diferentes localidades de la ciudad. La estructura de esta colección será:

-- Colección colegios_localidad_bogota:

<img src="https://drive.google.com/uc?export=view&id=1OCKraSc1bzxPUkaFNXrmqrRbOhaH9_BJ" width="50%">

In [ ]:
# Cargar dataframe con los datos de colegios por localidad en Bogotá
path_i = "./data/input/"
file_i = "colegios_bogota_localidad.csv"
df_colegios_bogota = pd.read_csv(path_i + file_i)

In [ ]:
# estructura del dataframe
df_colegios_bogota.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5073 entries, 0 to 5072
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   COD_LOCALIDAD  5073 non-null   int64
 1   NOM_LOCALIDAD  5073 non-null   object
 2   NOM_COLEGIO    5073 non-null   object
 3   NOM_SEDE       5073 non-null   object
 4   COD_DANE_TXT   5073 non-null   object
 5   COD_DANE       5073 non-null   int64
 6   CLASE          5073 non-null   object
 7   JORNADA        5073 non-null   object
dtypes: int64(2), object(6)
memory usage: 317.2+ KB

In [ ]:
# Creación de la coleccion icfes_colegios_bogota
db.drop_collection("icfes_colegios_bogota")
icfes_colegios_bogota  = create_collection("icfes_colegios_bogota", db)
load_collection(df_colegios_bogota.loc[df_colegios_bogota['JORNADA'] == 'MAÑANA'], icfes_colegios_bogota, list(df_colegios_bogota.columns), db)

*** creating collection icfes_colegios_bogota
done
*** loading collection Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'icfes_db_mlds'), 'icfes_colegios_bogota')
done

Sobre las colecciones se realiza creación de índices:

In [ ]:
db.icfes_estudiante_colegio.create_index( { "ESTU_CONSECUTIVO": 1 } )
db.icfes_estudiante_colegio.create_index( { "COLE_COD_DANE_ESTABLECIMIENTO": 1 } )
db.icfes_estudiante_colegio.create_index( { "COLE_COD_DEPTO_UBICACION": 1 } )
#
db.icfes_estudiante_estudiante.create_index( { "ESTU_CONSECUTIVO": 1 } )
db.icfes_estudiante_estudiante.create_index( { "ESTU_COD_RESIDE_DEPTO": 1 } )
#
db.icfes_estudiante_familia.create_index( { "ESTU_CONSECUTIVO": 1 } )
#
db.icfes_colegios_bogota.create_index( { "COD_DANE": 1 } )

'COD_DANE_1'

Finalmente, la estructura de la base de datos MongoDB se visualiza de la siguiente forma:

<img src="https://drive.google.com/uc?export=view&id=1z2sSsAHg7ZGPriwCqVd8I5CkdytUVh6N" width="100%">